apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: http://localhost:30093
    link.argocd.argoproj.io/external-link-title: "Grafana"
    link.argocd.argoproj.io/external-link-description: "Monitoring and Observability Dashboard"
    link.argocd.argoproj.io/external-link-icon: "📊"
spec:
  project: infrastructure
  source:
    repoURL: http://gitea.gitea.svc.cluster.local:3000/gitops/infrastructure.git
    path: grafana
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true