apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: registry
  labels:
    app: docker-registry
  annotations:
    link.argocd.argoproj.io/external-link: http://localhost:30087
spec:
  type: NodePort
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    nodePort: 30087  # Registry accesible en localhost:30087
  selector:
    app: docker-registry
