---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  annotations:
    managed-by: gitops
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  # Polling más rápido para desarrollo (30 segundos en lugar de 3 minutos)
  timeout.reconciliation: 30s
  timeout.hard.reconciliation: 60s
  # Configuración para repositorios Git
  repository.credentials: |
    - url: http://gitea.gitea.svc.cluster.local:3000
      type: git
  # Health checks optimizados
  resource.customizations.health.networking.k8s.io_Ingress: |
    hs = {}
    hs.status = "Healthy"
    hs.message = "Ingress is configured"
    return hs
  
  # External links for all GitOps UIs - 100% funcional
  application.links: |
    - url: http://localhost:30089
      title: Argo Workflows
    - url: http://localhost:30082  
      title: Grafana
    - url: http://localhost:30081
      title: Prometheus
    - url: http://localhost:30084
      title: Kubernetes Dashboard
    - url: http://localhost:30085
      title: Kargo
    - url: http://localhost:30086
      title: Argo Rollouts
    - url: http://localhost:30087
      title: Registry UI
