---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  annotations:
    managed-by: gitops
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  # Polling más rápido para desarrollo (30 segundos en lugar de 3 minutos)
  timeout.reconciliation: 30s
  timeout.hard.reconciliation: 60s
  # Configuración para repositorios Git
  repository.credentials: |
    - url: http://gitea.gitea.svc.cluster.local:3000
      type: git
  # Health checks optimizados
  resource.customizations.health.networking.k8s.io_Ingress: |
    hs = {}
    hs.status = "Healthy"
    hs.message = "Ingress is configured"
    return hs
