apiVersion: v1
kind: ConfigMap
metadata:
  name: ci-scripts
  namespace: argo-workflows
data:
  git-clone.sh: |
    #!/bin/sh
    set -e
    echo "🔍 Cloning repository..."
    git clone --depth=1 --branch="$BRANCH" "$REPO_URL" /workspace
    cd /workspace
    if [ -n "$COMMIT_SHA" ] && [ "$COMMIT_SHA" != "HEAD" ]; then
      echo "📌 Checking out commit: $COMMIT_SHA"
      git fetch --depth=1 origin "$COMMIT_SHA"
      git checkout "$COMMIT_SHA"
    fi
    echo "✅ Repository ready"
    ls -la

  docker-build-push.sh: |
    #!/bin/sh
    set -e
    echo "🐳 Building and pushing Docker image..."
    /kaniko/executor \
      --dockerfile=/workspace/Dockerfile \
      --context=/workspace \
      --destination="$IMAGE_REGISTRY/$IMAGE_NAME:$COMMIT_SHA" \
      --destination="$IMAGE_REGISTRY/$IMAGE_NAME:latest" \
      --insecure \
      --skip-tls-verify \
      --cache=true \
      --cache-ttl=24h
    echo "✅ Image pushed: $IMAGE_REGISTRY/$IMAGE_NAME:$COMMIT_SHA"

  update-manifests.sh: |
    #!/bin/sh
    set -e
    echo "📝 Updating Kubernetes manifests..."
    
    # Clone gitops repo
    cd /tmp
  git clone http://gitea.gitea.svc.cluster.local:3000/gitops/gitops-repo.git
  cd gitops-repo/gitops/applications/demo-app
    
    # Update image tag
  sed -i "s|image:.*|image: $REGISTRY/$IMAGE_NAME:$COMMIT_SHA|g" kustomization.yaml
    
    # Commit and push
    git config user.name "Argo Workflows"
    git config user.email "argo@gitops.local"
    git add .
    git commit -m "chore: update demo-app image to $COMMIT_SHA"
    git push
    
    echo "✅ Manifests updated and pushed"
