apiVersion: v1
kind: Service
metadata:
  name: argo-server-nodeport
  namespace: argo-workflows
  labels:
    app.kubernetes.io/name: argo-server
  annotations:
    argocd.argoproj.io/external-url: http://localhost:30091
spec:
  type: NodePort
  selector:
    app: argo-server
  ports:
    - name: web
      port: 2746
      targetPort: 2746
      nodePort: 30091
