---
# ServiceAccount for Argo Events Sensor
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sensor-sa
  namespace: argo-events

---
# Role to create Workflows in argo-workflows namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sensor-workflow-creator
  namespace: argo-workflows
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
      - get
      - list
      - watch

---
# RoleBinding to allow Sensor SA to create Workflows
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sensor-workflow-creator-binding
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: argo-events-sa
    namespace: argo-events
roleRef:
  kind: Role
  name: sensor-workflow-creator
  apiGroup: rbac.authorization.k8s.io
