apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gitea-workflow-trigger
  namespace: argo-events
spec:
  eventBusName: default
  # NOTE: Argo Events v1.9.7 bug - sensor-controller ignores this field
  # Deployment uses 'argo-events-sa' by default. Requires manual patch:
  # kubectl patch deployment -n argo-events <sensor-deployment> --type=json \
  #   -p='[{"op":"replace","path":"/spec/template/spec/serviceAccountName","value":"argo-events-sa"}]'
  serviceAccountName: argo-events-sensor-sa
  dependencies:
    - name: push-event
      eventSourceName: gitea-webhook
      eventName: demo-app
      filters:
        data:
          - path: header.X-Gitea-Event.0
            type: string
            value:
              - push
  triggers:
    - template:
        name: trigger-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: demo-app-ci-
                namespace: argo-workflows
                labels:
                  app: demo-app
                  triggered-by: argo-events
                  workflows.argoproj.io/controller-instanceid: default
              spec:
                serviceAccountName: argo-workflow-sa
                workflowTemplateRef:
                  name: ci-pipeline-template
                arguments:
                  parameters:
                    - name: repo-url
                      value: "http://gitea.gitea.svc.cluster.local:3000/gitops/demo-app.git"
                    - name: branch
                      value: "main"
                    - name: commit-sha
                      value: "unknown"
                    - name: image-name
                      value: "demo-app"
                    - name: registry
                      value: "docker-registry.registry.svc.cluster.local:5000"
          parameters:
            # Commit SHA desde webhook
            - src:
                dependencyName: push-event
                dataKey: body.after
              dest: spec.arguments.parameters.2.value
            # Branch desde webhook
            - src:
                dependencyName: push-event
                dataKey: body.ref
              dest: spec.arguments.parameters.1.value
            # NOTA: NO usamos body.repository.clone_url porque trae localhost
            # En su lugar, usamos el valor estático definido en spec.arguments.parameters[0]
