apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

resources:
  # Install oficial de Sealed Secrets Controller
  # Incluye: CRDs, controller deployment, RBAC, service
  - install.yaml
