---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-rollouts-extra
  labels:
    app.kubernetes.io/part-of: argo-rollouts
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/component: rollouts-controller
rules:
- apiGroups:
  - argoproj.io
  resources:
  - analysisruns
  - analysistemplates
  - clusteranalysistemplates
  - experiments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-rollouts-extra
  labels:
    app.kubernetes.io/part-of: argo-rollouts
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/component: rollouts-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-rollouts-extra
subjects:
- kind: ServiceAccount
  name: argo-rollouts
  namespace: argo-rollouts
