apiVersion: v1
kind: Service
metadata:
  name: app-calendar
  namespace: app-calendar
  labels:
    app: app-calendar
spec:
  type: NodePort
  selector:
    app: app-calendar
  ports:
    - name: http
      port: 80
      targetPort: 4000
      nodePort: 30178
      protocol: TCP
