apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
  namespace: hello-world
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World App</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                text-align: center;
                padding: 50px;
                background-color: #f0f0f0;
            }
            h1 {
                color: #333;
                font-size: 3em;
            }
            .container {
                max-width: 800px;
                margin: 0 auto;
                background: white;
                padding: 40px;
                border-radius: 10px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 Hello World!</h1>
            <p>Esta es una aplicación de ejemplo desplegada con ArgoCD</p>
            <p><strong>Desplegado desde:</strong> GitOps con ArgoCD</p>
            <p><strong>Namespace:</strong> hello-world</p>
            <p><strong>Fecha:</strong> $(date)</p>
        </div>
    </body>
    </html>