apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows

resources:
  # 1. Install oficial (CRDs, controller, server, RBAC base)
  - install.yaml
  
  # 2. Service NodePort (acceso externo UI)
  - service-nodeport.yaml
