apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: demo-app
    newName: docker-registry.registry.svc.cluster.local:5000/demo-app
    newTag: latest
