apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  description: "Infraestructura y herramientas GitOps gestionadas por ArgoCD"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'  # 🎯 Permitir cualquier namespace para máxima flexibilidad GitOps
      server: https://kubernetes.default.svc
    - namespace: kargo
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'