apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: demo-api
  labels:
    app: demo-api
    version: v2.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
        version: v2.0.0
    spec:
      containers:
        - name: api
          image: demo-api:v2.0.0
          # Cuando usamos un registry local debemos permitir que Kubernetes haga pull
          # si la imagen está disponible remotamente. `IfNotPresent` funciona bien
          # para entornos donde las imágenes se publican en un registry local.
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: production
            - name: VERSION
              value: v2.0.0
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
