---
# ApplicationSet para GitOps Tools sin UI (herramientas que no tienen interfaz web)
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-tools-no-ui
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: http://gitea.gitea.svc.cluster.local:3000/gitops/gitops-tools.git
      revision: HEAD
      directories:
      - path: argo-events
      - path: argo-image-updater  
      - path: redis
      # sealed-secrets is bootstrapped directly (not via ArgoCD) to avoid circular dependency
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: gitops-tools
      source:
        repoURL: 'http://gitea.gitea.svc.cluster.local:3000/gitops/gitops-tools.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
