---
# Application principal que gestiona la configuración interna de ArgoCD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/managed-by: bootstrap
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd-config
  sources:
    - repoURL: http://gitea.gitea.svc.cluster.local:3000/gitops/argo-config.git
      targetRevision: HEAD
      path: projects
      directory:
        recurse: true
    - repoURL: http://gitea.gitea.svc.cluster.local:3000/gitops/argo-config.git
      targetRevision: HEAD
      path: applications
      directory:
        recurse: true
    - repoURL: http://gitea.gitea.svc.cluster.local:3000/gitops/argo-config.git
      targetRevision: HEAD
      path: repositories
      directory:
        recurse: true
    - repoURL: http://gitea.gitea.svc.cluster.local:3000/gitops/argo-config.git
      targetRevision: HEAD
      path: configmaps
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      namespace: argocd
      jsonPointers:
        - /spec/syncPolicy/automated
        - /metadata/annotations/argocd.argoproj.io~1refresh
        - /operation
