---
# ApplicationSet para Custom Apps (activado solo si ENABLE_CUSTOM_APPS=true)
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: custom-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: http://gitea.gitea.svc.cluster.local:3000/gitops/applications.git
      revision: HEAD
      directories:
      - path: '*'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: applications
      source:
        repoURL: 'http://gitea.gitea.svc.cluster.local:3000/gitops/applications.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
