apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-reloj
  namespace: app-reloj
  labels:
    app: app-reloj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-reloj
  template:
    metadata:
      labels:
        app: app-reloj
    spec:
      containers:
      - name: app-reloj
        # Imagen base simplificada; Kustomize (kustomization.yaml) gestionará registry y tag (newName/newTag)
        image: app-reloj:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
