apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: app-reloj
    newName: docker-registry.registry.svc.cluster.local:5000/app-reloj
    newTag: latest
