apiVersion: v1
kind: Service
metadata:
  name: app-reloj
  namespace: app-reloj
  labels:
    app: app-reloj
  annotations:
    link.argocd.argoproj.io/external-link: 'http://localhost:30150'
spec:
  type: NodePort
  selector:
    app: app-reloj
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30150  # Custom apps range
