---
# Ultra Simple OPA Demo - No Gatekeeper Complexity
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policies
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: opa-demo
data:
  basic-policy.rego: |
    package kubernetes.demo
    
    # Simple policy to log deployment information
    default allow = false
    
    allow {
      input.kind == "Pod"
      input.metadata.namespace != "kube-system"
    }
    
    # Demo check - deployments should have labels
    violation[msg] {
      input.kind == "Deployment" 
      count(input.metadata.labels) == 0
      msg := sprintf("Deployment '%s' in namespace '%s' should have labels", [input.metadata.name, input.metadata.namespace])
    }
    
    # Simple validation rule  
    warn[msg] {
      input.kind == "Service"
      input.spec.type == "LoadBalancer"
      msg := "Consider using NodePort for local development instead of LoadBalancer"
    }