apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: demo-app
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: gitops-demo

namespace: demo-app-dev
