apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgABCtq5qfaAxKQ8AYDttiuIWpHLMshDRkJDBylxrjoWm1XG9SMaOkBrOVSK703rkBQwkiYzAjRukX/PQwbksuXz/RCd89QparuKe1gmyTA3SinbshPIrVQfJz5JHQxNnPc2GFrhEseYukSJykWTcWwg0xmggWOTmQwSBkNzB7p8RwXHATfjZYWskX+CoOWNpKiKqYyUwwmKdtABK3Dh2osVDKNIYsEnwLt5R2jc2Pv3hlPqyOEE8N+8IZby/nwiE1t6iCPYPvgaax4VSr+WxJfFITNbD6hNsAeq6yUhQjUD30VjQUcouIdMNgMDlJhr5g2lZhU5OHMJ0383sC8lz320gfOPGPPX9Pnq/tGD9BJbI/Mj6cMDyvUoDf9ikrWZA1DApcXl+P+fb7BjCSn1foooI3bv10Y18quu0xnJwuBX0brijqmYL72ajc7G74nA9KoUg3eqrOyURFcnUo0Q9pvhg/dobxwTqbA5ItUkX1Vicmxh8bInMjeuHPjxeHBMwPbRwltadknoKE19XyRCIb55f74Z4pmKsgFaV1VA5t4Md8L6etubiNKvFXaO8Oq0mCDi37mvfKhbs27LsHyMAGsoW4sjwAZeeBzDy68S3cS70cu44mrfwquyja6eyFZyE70af9hJuSkffdmh3164InQQ0e0Z+i7JGtrqRwQCTQOu0PMvLIXYD3iqQdbl5WXekUn/YkGL5rE=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: grafana
---
