apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgASbgaj9PU2ERkgXocsXF1EZ26zJTLzhYyYLsMhcmNwDlzSjhEeIjQFLiDIFz4xp480pwAQ536qUSp7hy7AIkQLEKRsXQcnMwNk0+n27PoO3ARADWlbaY87M78668xiL29iU6QSNA/Knb4c1tfdz7lSst0yk9CPo7o6wC4yXDL9i5wxV3D4xQ9PQdBp7eeQPipCYeDy1kL4g77EDscY9uKXqZLjFaZsQzBJif+pV8MJSAopaD+gx1v4G4wR5h447bHPrZS1DfCREvUQPrFP5Luahnc8o4YKTaH+42cm8VVO2P/ESu7MdzBDtXVfJdD36pW6aaLZC7URulzlys4kkN6iIMYIKgg4ahojx39ZC/Lk9STNH1AGKX1pKw3fduz5TJj363h4dPhFnIKXPPH2H+hkmyBkGxyFlAGu6ZwUQDEMwCSobixrLwgLBg25RcbKHPZQRW/UxRf3DDsmGd7ikf64oLFfSe9hYceMnZ+EI6Em+WmSSIqy1Zk2KYlbe7TNE43kSSkZ++A3c51zlc4gJ3xhT1OYiiEmIQnBJKkF9zTNolOdT3/v6XMdATdUMdyNjIu0nnDLkmx21faUsv9TO5OiyQIvtOV6kdfa5xyBEkVQ940J9wXiA/lhortuu5jR3X1Zoshe9q9Fhz21RojuHnPKVhdh//XPX6T7koYt73P5NZCIQ2oy/urFbAadGdA2WnGdnImEppo=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: grafana
---
