---
# Secret simple para entorno de aprendizaje
# Como Grafana tiene anonymous auth, este secret es opcional
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-options: Skip=true
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: "gitops"
