apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure tools and observability stack
  sourceRepos: 
  - '*'
  destinations:
  - namespace: 'monitoring'
    server: https://kubernetes.default.svc
  - namespace: 'kubernetes-dashboard'
    server: https://kubernetes.default.svc
  - namespace: 'ingress-nginx'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: admin
    description: Infrastructure admin access
    policies:
    - p, proj:infrastructure:admin, applications, *, infrastructure/*, allow
    - p, proj:infrastructure:admin, repositories, *, *, allow
    groups:
    - infrastructure-admins