---
# Canary Rollout Example - Hello World
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world-canary
  namespace: hello-world
  labels:
    app: hello-world-canary
    gitops.example: "canary-deployment"
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20    # 20% traffic to new version
      - pause:
          duration: 30s  # Wait 30 seconds
      - setWeight: 40    # 40% traffic to new version  
      - pause:
          duration: 30s  # Wait 30 seconds
      - setWeight: 60    # 60% traffic to new version
      - pause:
          duration: 30s  # Wait 30 seconds  
      - setWeight: 80    # 80% traffic to new version
      - pause:
          duration: 30s  # Wait 30 seconds
      - setWeight: 100   # 100% traffic to new version (complete)
  selector:
    matchLabels:
      app: hello-world-canary
  template:
    metadata:
      labels:
        app: hello-world-canary
        version: canary
    spec:
      containers:
      - name: hello-world
        image: hello-world-modern:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: APP_MODE
          value: "canary"
        - name: VERSION
          value: "v2.0.0"
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-canary
  namespace: hello-world
  labels:
    app: hello-world-canary
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30087
    name: http
  selector:
    app: hello-world-canary