apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app-prod

resources:
  - ../../base

replicas:
  - name: demo-app
    count: 5

images:
  - name: localhost:30087/demo-app
    newTag: latest

commonLabels:
  environment: production

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
    target:
      kind: Deployment
      name: demo-app
