apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  nats:
    native:
      # Para entorno local/Kind no necesitamos HA
      replicas: 1
      # Desactivar autenticación para evitar secretos requeridos en demo
      auth: none
