apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app: grafana
spec:
  project: gitops-tools
  source:
    repoURL: http://gitea:3000/gitops/gitops-tools.git
    targetRevision: master
    path: grafana/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true