apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: http://localhost:30094
    link.argocd.argoproj.io/external-link-title: "Kargo UI"
    link.argocd.argoproj.io/external-link-description: "GitOps Continuous Promotion Tool"
    link.argocd.argoproj.io/external-link-icon: "🚢"
spec:
  project: infrastructure
  source:
    repoURL: http://gitea.gitea.svc.cluster.local:3000/gitops/infrastructure.git
    path: kargo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true