apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: custom-apps
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  description: "Aplicaciones personalizadas del proyecto (visor-gitops, app-reloj, etc.)"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
