---
# ApplicationSet para custom-apps (visor-gitops, app-reloj)
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: custom-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: http://gitea.gitea.svc.cluster.local:3000/gitops/custom-apps.git
      revision: HEAD
      directories:
      - path: visor-gitops
      - path: app-reloj
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd.argoproj.io/external-url: 'http://localhost:{{if eq .path.basename "visor-gitops"}}30098{{else}}30099{{end}}'
    spec:
      project: custom-apps
      source:
        repoURL: 'http://gitea.gitea.svc.cluster.local:3000/gitops/custom-apps.git'
        targetRevision: HEAD
        path: 'gitops-tools/{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
