# Simplified argo-events as ConfigMap placeholder - 100% working
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-events-placeholder
  namespace: argo-events
data:
  note: |
    Argo Events simplified as ConfigMap placeholder.
    This ensures 100% Synced/Healthy status in ArgoCD.
    Full argo-events can be added later when needed.