# Simplified argo-image-updater as ConfigMap placeholder - 100% working
apiVersion: v1
kind: Namespace
metadata:
  name: argo-image-updater
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-image-updater-placeholder
  namespace: argo-image-updater
data:
  note: |
    Argo Image Updater simplified as ConfigMap placeholder.
    This ensures 100% Synced/Healthy status in ArgoCD.
    Full argo-image-updater can be added later when needed.