apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-api
  namespace: kargo
  labels:
    app.kubernetes.io/name: kargo
    app.kubernetes.io/component: api
data:
  KARGO_API_LISTEN_ADDRESS: ":8080"
  KARGO_API_GRPC_LISTEN_ADDRESS: ":9090"
  KARGO_API_LOG_LEVEL: "info"
