apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: http://localhost:30092
    link.argocd.argoproj.io/external-link-title: "Prometheus"
    link.argocd.argoproj.io/external-link-description: "Metrics Collection and Alerting"
    link.argocd.argoproj.io/external-link-icon: "🔥"
spec:
  project: infrastructure
  source:
    repoURL: http://gitea.gitea.svc.cluster.local:3000/gitops/infrastructure.git
    path: prometheus
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true